/**
 * Piedmont Park · MOUNTAIN_LORE Corpus
 * Zone-keyed narrative text for pretext wall rendering.
 * Source: pretext_piedmont_wall_text.txt (researched corpus)
 */

export const PIEDMONT_LORE: Record<string, string[]> = {
  lake: [
    'At the south end of Lake Clara Meer, the city turns upside down and holds still just long enough for you to notice the fraud. Glass towers hang below the waterline with their windows broken into ripples by a duck\'s wake. A single feather drifts over the reflected skyline as if scale has failed here, as if one white filament can cross Midtown.',
    'The lake does not feel wild. It feels shaped, retained, persuaded into calm by stone edges, railings, docks, and the habits of people who come here expecting surface. At the margin the water reads cooler than the sunlit path because springs still feed this basin from below, and the air immediately above it has that faint mineral softness of shaded standing water rather than the sharper smell of a chlorinated pool.',
    'Children throw bread and the bread lands with small flat sounds that carry farther than expected. Mallards pivot first, then accelerate. The water darkens where their bodies cross the reflection. On the southern border trail, witch-hazel and low shade hold a dimmer green than the exposed lawn. Around the lake, sweetbay magnolia and southern magnolia thicken the edge with glossy leaves that read almost lacquered under noon light.',
    'To the north the ground opens toward the Active Oval, which feels louder even when you cannot hear it yet. To the west the Stone Bridge and its masonry weight interrupt the softer geometry of shoreline. To the east the BeltLine keeps moving in a straight, former-industrial sentence, while this water keeps answering in curves.',
    'You stand where Atlanta likes to believe in reconciliation between park and skyline, but the reconciliation is optical. The buildings are only present here because the lake consents to hold them. When the wind arrives, the whole arrangement tears, and the city returns to the far bank where it belongs.',
  ],
  lake_hist: [
    'Before there was a named lake here, this ground belonged to older Indigenous lifeways and to a wetter system of springs, creek movement, and forested slope. The park\'s current planning documents explicitly place Piedmont Park within a longer sequence that begins with Indigenous presence before settler farming and exposition spectacle, and Atlanta history institutions frame this broader region as Muscogee and Cherokee homeland before removal.',
    'In 1834 Samuel and Sarah Walker purchased the land, and the forest was cleared into farm ground. A spring-fed pond already structured this low area by 1887, and in 1895 it was enlarged to roughly its current 11.5-acre size and named Clara Meer for the Cotton States and International Exposition, which ran 100 days and drew about 800,000 visitors.',
    'The lake then turned into civic leisure infrastructure. A wooden bathhouse arrived in 1911, the current stone bathhouse replaced it in 1926, and the 1910 rest house near the 12th Street gate was restored in 1996 as the Visitor Center. The water that now reflects towers once held swimmers, diving platforms, sunning platforms, and a giant double water slide.',
  ],
  meadow: [
    'The Active Oval is not one green thing but a negotiation among speeds. A runner cuts the .52-mile track in an even loop. A dog breaks diagonally across a picnic blanket\'s edge. A frisbee takes the long arc of a thought someone had only half on purpose. Two soccer fields, two softball fields, and two sand volleyball courts sit inside the larger illusion that this is just open grass.',
    'From the center, the park behaves like a compass. Lake Clara Meer pulls south with reflected glass and cooler air. The BeltLine hardens the eastern edge into motion and passing faces. The Botanical Garden rises north as curated canopy and ticketed order. Westward, the dog park rattles with contained impact, and beyond it the tree line thickens before giving way again.',
    'The ground tells on the body. Chlorophyll ruptures under cleats and bare feet and smears into fabric with plant wax and dust, making the green stain less a color than a chemistry problem. Dry-season turf scratches white at the tips; after rain, the field holds darker seams where compaction delays drainage by a few hours and the soil smells metallic and fungal at once.',
    'The trees at the margins behave like stage rigging for the meadow. Hackberry stands east of the Oval. Eastern redcedar anchors the southwest corner. Tulip poplar lifts a taller, cleaner vertical line toward the north end. Their canopies do not close over the field; they frame it, withholding shade so that the Oval keeps its bright, exposed social function.',
    'Nothing here is private, but everything is briefly claimed. A towel makes a kingdom for twenty minutes. A kickball team annexes one side of the grass. Someone lies flat and looks up long enough for the skyline to disappear behind leaf edges. The place works because ownership never holds. It is always being returned.',
  ],
  meadow_hist: [
    'This open center was once forest, then farm. Official park history places a Walker family cabin on what is now the Active Oval, and the cleared land became working agricultural ground long before it became recreation field or civic lawn.',
    'By the exposition era, the land had been graded and reimagined at a much larger civic scale. The broader fair landscape of 1895 drew roughly 800,000 visitors. Current park planning documents place the original Negro Building near the present-day meadow next to Charles Allen Drive, and Booker T. Washington\'s Atlanta Exposition Address was delivered nearby at the former exposition auditorium on September 18, 1895, before a segregated audience.',
    'As the fairgrounds gave way to city park, Olmsted Brothers planning principles shaped the larger landscape logic around the meadow: meandering paths, changing elevations, open fields set against trees and water, and distinct zones of use. The present recreational center still carries that layered history of spectacle, segregation, reform, and public gathering under one wide sheet of grass.',
  ],
  beltline: [
    'The BeltLine at the park\'s eastern edge feels less like a path than a seam that was never fully closed. The pavement is wide, deliberate, and social, but the corridor still remembers freight geometry. You move through a cut line in the city where steel once decided direction and now pedestrians, scooters, bikes, and strollers negotiate it by glance, shoulder angle, and speed.',
    'To the west, Piedmont Park loosens into tree canopy and the long breathing room of Lake Clara Meer. To the east, Monroe Drive and the city\'s harder edges keep pressing close. The murals, planters, railings, and lighting do not erase that pressure; they stage it. This is one of those Atlanta places where adaptive reuse is not a slogan but a ground condition under your feet.',
    'The old rail logic survives in the straightness. Sound travels differently here. A laugh arrives from behind before the person does. Rubber tires hiss on concrete. Dog tags ring once and vanish. In summer the air holds sunscreen, overheated brake dust from nearby traffic, and the sweet chemical edge of aerosol paint when fresh work has gone up along the wall surfaces.',
    'The trail makes the park legible by slicing past it. Look west and you understand where the lake sits, where the Bridge interrupts the ravine system, where the Active Oval opens, where the Garden begins its stricter argument about what nature should look like. The corridor is a viewing instrument as much as a route.',
    'You are moving inside a former industrial sentence that has been rewritten as public leisure without fully deleting its first draft. That is why the place feels charged. The ghost underneath is still grammatical.',
  ],
  beltline_hist: [
    'The Eastside Trail is the first finished section of the Atlanta BeltLine in the old rail corridor, and today it runs from the tip of Piedmont Park to Reynoldstown. Its present identity is clean and civic, but the larger loop comes from multiple railroad sections laid after the Civil War rather than a single original line.',
    'For the east side in particular, historical reporting traces the corridor around Piedmont Park to rail laid in the 1870s by the Atlanta & Richmond Air-Line Railway, later commonly folded into Southern Railway history. Freight once moved through here instead of joggers, and Monroe Drive delays once meant trains instead of stroller traffic.',
    'The public transformation becomes tangible in the BeltLine timeline: West End Trail in 2008, more trail openings in 2010, and then the Eastside Trail\'s 2012 debut, which demonstrated the project\'s potential and helped turn neglected rail land into one of Atlanta\'s busiest public corridors. What now reads as amenity began as infrastructure and returned as public space.',
  ],
  garden: [
    'The Botanical Garden is curated nature with a straight face and a large maintenance budget. Labels stand beside roots and stems like small acts of official recognition. Water is directed. Bloom time is anticipated. Shade is managed. The place teaches you that \u201cnatural\u201d can also mean scheduled, accessioned, mapped, and under quiet surveillance.',
    'The scale changes as you move through it. One leaf carries veins fine as handwriting. One orchid bloom behaves like a staged event. Then the sightline lifts and the city reappears beyond the canopy, making the whole Garden feel like a temporary treaty between horticulture and Midtown real estate. North of the Active Oval, this is where the park\'s looser ecology turns into collection.',
    'Storza Woods keeps the strongest counterargument alive. Here the air cools and thickens. Light arrives filtered through hardwood canopy in green-gold sheets rather than open-field brightness. The Kendeda Canopy Walk suspends you above the understory for 600 feet, and the body suddenly understands vertical forest structure instead of just looking at trees from below.',
    'Every path here asks what kind of nature you trust more: the one with names, edges, and irrigation plans, or the one that keeps trying to reassert itself in leaf litter, fungal damp, and root heave. Even the scent divides along those lines. A bed of cultivated bloom gives perfume first. The woods answer later with tannin, wet bark, and decomposing cellulose.',
    'From here, 14th Street is close enough to remind you that the whole labyrinth sits inside traffic. Piedmont Avenue stays to the west. The BeltLine keeps working the city\'s outer seam nearby. The Garden does not escape Atlanta. It edits it.',
  ],
  garden_hist: [
    'The northern park landscape now occupied by the Garden belongs to the same longer chronology the park\'s own planning documents describe: Indigenous lifeways, settler farmland, exposition ground, Olmsted influence, and modern civic landscape. Atlanta history institutions frame the broader region as Muscogee and Cherokee homeland before forced removal in the early nineteenth century.',
    'By the Walker era, this land had been folded into settler agriculture. Official park history documents the Walkers\' 1834 purchase and later Benjamin Walker ownership, and the Garden\'s own institutional history begins much later, with a citizen push in 1973 and the incorporation of Atlanta Botanical Garden, Inc. in 1976 on park land leased by the city.',
    'The result is a layered northern edge where one of Atlanta\'s most formal plant institutions sits inside a park whose larger circulation and spatial logic were heavily shaped by the Olmsted Brothers\' 1912 plan and its long afterlife. The Garden is new by comparison, but it grows from older lines of power, access, design, and land transformation.',
  ],
  bridge: [
    'The bridge is where the park changes tense. South of it, the lake accepts skyline and event logic. North of it, the land thickens, cools, and begins to remember creek, slope, and older shade. The body notices first in the sound. Footsteps on masonry return a shorter echo than footsteps on packed path. Voices narrow. Water below speaks in fragments.',
    'Stone and moisture hold each other here. The rail or parapet stays cooler than the air well into afternoon. Lichen grips the rougher surfaces in pale maps. In the seams, grit gathers with sweetgum star-fragments, pollen paste, and the black powder of brake dust carried in from the nearby roads. This is a threshold built out of both geology and urban residue.',
    'Light changes under the canopy around the crossing. It stops being flat park light and becomes filtered, striated, brief. Leaves cut the sun into moving strips that travel over the stone face and vanish. The ravine below keeps a different clock. Water there does not flash like the open lake; it glints and disappears, glints and disappears.',
    'To one side the Active Oval waits in its exposed social brightness. To another the dog park works the Chaos Perimeter into noise and impact. Lake Clara Meer stays just behind you with its broader, smoother surface. The BeltLine remains east, straightening the city into a line whenever the park threatens to become too irregular.',
    'You cross and the park edits your pace without asking permission. That is what a good bridge does. It makes movement feel chosen after the fact.',
  ],
  bridge_hist: [
    'The clearest official bridge chronology in Piedmont Park belongs to the Park Drive Bridge, built in 1916 after the city had purchased the former exposition grounds and after the Olmsted Brothers had been brought in to prepare their master plan. Park history and the Conservancy\'s Olmsted essay both treat that bridge as part of the long implementation of early twentieth-century landscape thinking rather than an 1895 exposition leftover.',
    'That matters because the stone story of this park is easy to compress into one myth. In fact, the exposition left balustrades and stair remnants, the Olmsted era shaped later circulation and bridges, and the broader city built itself through harder systems of labor and extraction that included convict labor elsewhere in Atlanta and granite economies tied to places like Stone Mountain. The park holds those histories unevenly, in fragments rather than in one clean monument.',
    'So the bridge zone reads best as a threshold between layers: exposition residue, city-park redesign, Olmsted influence, and later preservation. It is less useful as a single-origin relic than as a crossing where multiple Atlanta infrastructures still touch each other.',
  ],
  dogpark: [
    'The dog park is a machine for converting private attachment into public noise. Three fenced acres hold impact, speed, hierarchy, apology, and instant alliance inside chain-link diamonds that shimmer silver in hard light. The fence is not scenery. It is the entire concept. Without it, the place dissolves back into ordinary park.',
    'The ground shows repeated use in layers. Dust rises first from the dry run lanes near the gate. Damp soil survives longer in the shadier corners. Fur collects in the fence wire. Water spatters darken the dirt around the dog-level spigots. A tennis ball, half-collapsed, waits in the exact spot where nobody remembers losing it. Bark arrives in volleys rather than singles.',
    'Separate enclosures sort the park by body mass, but the real sorting is temperamental. One dog runs elliptical loops with mathematical devotion. Another stands chest-deep in scent work near the perimeter and reads the world through urine and trampled grass. Owners lean on benches and conduct that strange half-conversation where attention is always split between language and motion.',
    'The bridge overhead and the nearby wetlands keep the place from becoming purely recreational. Shade falls in angled stripes. The air sometimes carries wet-earth cool from Six Springs and sometimes the hot metal smell of sun-struck fencing. Under the Park Drive bridge the sound thickens and rebounds, so one bark can momentarily sound like six.',
    'From here the Active Oval sits east in a different form of sanctioned play. The Garden is close enough to imagine but far enough to remain another class system of animal and plant behavior entirely. The Bridge and the Chaos Perimeter belong to this place because chaos is exactly what has been admitted, funded, fenced, and maintained.',
  ],
  dogpark_hist: [
    'This area sits inside the park\'s long transformation from farm to exposition ground to municipal recreation landscape. What can be stated confidently from official sources is the broader chronology: Walker farmland in the nineteenth century, the 1895 exposition across the park, city purchase in 1904, Olmsted influence after 1911, and later recreational specialization.',
    'The modern off-leash dog parks are a much newer layer and are now described by the Conservancy as three acres beneath the Park Drive bridge with separate large- and small-dog areas, adjacent to the Education Garden and Six Springs Wetlands. In other words, this is a contemporary civic invention inserted into older hydrological and circulation systems.',
    'What used to gather here under earlier regimes was fairgoing, passage, labor, and later park traffic. What gathers now is barking, ritualized play, and the strange democracy of leash law suspended inside the fence. The form changes; the park keeps specializing space.',
  ],
  building: [
    'The restroom buildings at the park edge are blunt little truths. Their block walls, vents, and heavy doors admit that a public park is not only trees and views but plumbing, mops, tile, drains, paper stock, and the steady choreography of people arriving with urgency and leaving relieved. Even from twenty feet away you can smell soap, wet concrete, and the metallic ghost of tap water drying on steel.',
    'The pump houses and utility sheds are quieter, almost embarrassed by their own necessity. They sit behind shrubs or beside service paths in a green that park departments favor because it tries to disappear without actually succeeding. Their paint is a bureaucratic green, somewhere between leaf and oxidized metal, chosen not for beauty but for compliance with the background.',
    'The pool house and bathhouse lineage stays written in thicker walls and older proportions. Stone, steps, and roofline carry a formality that newer service structures do not bother with. Water has always demanded architecture here. First the lake needed changing rooms and support space, then the pool required deck rules, drains, storage, lifeguard sightlines, and the hard seasonal rhythm of opening and closure.',
    'The visitor center at the lake edge behaves differently. It receives. It frames. It explains. People step inside to orient themselves and come back out with the park newly sorted into names and routes. It turns landscape into itinerary, then releases you again toward Lake Clara Meer, the Bridge, the Active Oval, or the Garden.',
    'Gazebos are the park\'s small performances of public ornament. Their columns and roofs make temporary rooms out of air. They sharpen the act of standing still. A wedding uses them one way, a rain pause another, a tired parent another. Structure here is less about shelter than about giving pause an outline.',
    'The benches with brass memorial plaques work more slowly. Sun heats the metal until the engraved names are warmer than the wood slats beneath them. A person sits because their knees need the bench, then reads because the plaque insists that leisure has ancestry. The park fills with these tiny dedications, each one fastening private grief or gratitude to public duration.',
    'Padlocked utility boxes hold the opposite feeling. They say access exists, but not for you. The lock, hinge, warning sticker, and conduit speak in the terse grammar of maintenance culture. Every beautiful public landscape rests on this closed vocabulary of amperage, valves, irrigation timing, and repair schedules.',
    'The drinking fountains complete the lesson. Water leaves the nozzle in a clean arc that follows a parabola the child does not yet know the equation for. Their push buttons resist with a little spring force, then release a silver curve into hot afternoon. The park teaches physics constantly and without ceremony.',
  ],
}
